[[plugins]]
repo = 'skanehira/preview-markdown.vim'
[[plugins]]
repo = 'gabrielelana/vim-markdown'
[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = ''' " {{{
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_fmt_autosave = 1
let g:go_highlight_fields = 1
let g:neocomplete#enable_at_startup = 1
''' # }}}

