vim.opt.encoding = "utf-8"
vim.opt.fileencodings = "utf-8,iso-2022-jp,euc-jp,sjis"
vim.opt.cursorline = true
vim.opt.number = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.tabstop= 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.shiftwidth = 4
vim.opt.clipboard = "unnamed"
vim.opt.laststatus = 2
vim.opt.virtualedit= "block"
vim.opt.wildmenu = true
vim.opt.history= 100
vim.opt.showcmd = true
vim.opt.backspace = "indent,eol,start"
vim.opt.shell = "zsh"
vim.opt.showtabline= 2
