[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']
hook_source = ''' " {{{
    let g:terraform_align=1
    let g:terraform_fold_sections=0
    let g:terraform_fmt_on_save=1
''' # }}}

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = ''' " {{{
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_fmt_autosave = 1
let g:go_highlight_fields = 1
let g:neocomplete#enable_at_startup = 1
''' # }}}

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']
